// /app/styles/profileStyles.ts
import { StyleSheet } from 'react-native';

const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 16,
    paddingTop: 64, // match Discover page top spacing
    paddingBottom: 40, // add or increase this value
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  profileSection: { alignItems: 'center' },
  avatar: { width: 100, height: 100, borderRadius: 50, marginBottom: 8 },
  username: { color: '#333', fontSize: 20, fontWeight: 'bold', marginBottom: 8 },
  stats: { flexDirection: 'row', justifyContent: 'space-around', width: '100%', marginVertical: 12 },
  statItem: { alignItems: 'center' },
  statNumber: { color: '#333', fontSize: 18 },
  statLabel: { color: 'gray', fontSize: 12 },
  bioButton: {
    backgroundColor: '#fb7a20',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 10,
    marginBottom: 20,
  },
  bioButtonText: { color: '#fff' },
  storesContainer: { flex: 1 },
  sectionHeader: { color: '#fb7a20', fontSize: 18, marginVertical: 10 },
  storeItem: { color: '#333', paddingVertical: 5, paddingLeft: 10 },
  modalContainer: {
    backgroundColor: '#fff',           // pure white for a clean look
    padding: 24,
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '70%',
    borderTopLeftRadius: 20,           // rounded corners on left side
    borderBottomLeftRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: -2, height: 0 },
    elevation: 8,
    borderLeftWidth: 1,
    borderColor: '#eee',               // lighter border
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.15)',
  },
  modalItemText: {
    color: '#fff',
    fontSize: 18,
    marginLeft: 16,
  },
  findFriendsStatus: { color: '#fb7a20', marginTop: 24, textAlign: 'center', fontSize: 16 },
  findFriendsUserCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 16, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.06, shadowOffset: { width: 0, height: 2 }, shadowRadius: 6, elevation: 2 },
  findFriendsAvatarCircle: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#f7f7f7', justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  findFriendsAvatarImageWrapper: { width: 48, height: 48, borderRadius: 24, overflow: 'hidden' },
  findFriendsAvatarImage: { width: 48, height: 48, borderRadius: 24 },
  findFriendsUsername: { color: '#fb7a20', fontWeight: 'bold', fontSize: 18 },
  // Chat/Conversation styles
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'flex-end',
  },
  fullChatModal: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    flex: 1,
    overflow: 'hidden',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: '#fff',
    minHeight: 56,
    paddingBottom: 8,
    paddingHorizontal: 12,
    marginTop: 8, // Lower the chat header just below the status bar
  },
  chatBackButton: {
    padding: 0,
    marginRight: 8,
    marginTop: 0,
    alignSelf: 'flex-start',
  },
  chatTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
    marginLeft: 12,
  },
  chatMessages: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  chatMessageBubble: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    alignSelf: 'flex-start', // incoming messages on left
    maxWidth: '80%',
  },
  outgoingMessage: {
    alignSelf: 'flex-end', // outgoing messages on right
    backgroundColor: '#fb7a20',
  },
  punchoMessage: {
    backgroundColor: '#ffa366', // lighter orange
    alignSelf: 'flex-start',
  },
  chatMessageText: {
    fontSize: 15,
    color: '#222',
  },
  chatMessageTime: {
    fontSize: 11,
    color: '#666', // darker timestamps
    marginTop: 4,
    textAlign: 'right',
  },
  chatInputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    backgroundColor: '#fff',
    marginBottom: 16, // make input bar higher
  },
  chatInput: {
    flex: 1,
    fontSize: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    color: '#222',
  },
  sendButton: {
    padding: 8,
  },
  // Messages modal styles
  messagesModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    height: '45%', // Make the messages modal smaller
    position: 'absolute',
    left: 0,
    right: 0,
    top: '55%', // Position it lower on the screen
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  messagesContent: {
    paddingHorizontal: 20,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 20,
  },
  modalScrollView: {
    paddingHorizontal: 20,
  },
  conversationPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginBottom: 16,
    shadowColor: '#fb7a20',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f7e7d7',
  },
  conversationAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#fff6ee',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 18,
    borderWidth: 2,
    borderColor: '#fb7a20',
  },
  conversationName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fb7a20', // orange accent for Puncho, override in render if needed
    marginBottom: 2,
  },
  conversationLastMessage: {
    fontSize: 15,
    color: '#888',
    marginTop: 2,
    flex: 1,
  },
  conversationLastTime: {
    fontSize: 13,
    color: '#bbb',
    marginLeft: 8,
    alignSelf: 'flex-end',
  },
  unreadDotSmall: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#fb7a20',
    marginLeft: 12,
    borderWidth: 2,
    borderColor: '#fff',
    alignSelf: 'center',
  },
  messagesButton: {
    position: 'relative',
    padding: 4, // Add padding for the notification badge
  },
  unreadDot: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#fb7a20', // Changed from ORANGE to #fb7a20
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    paddingHorizontal: 4,
  },
  unreadCount: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  // Notification styles
  notificationItem: {
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  notificationSender: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222',
  },
  notificationTime: {
    fontSize: 12,
    color: '#999',
  },
  notificationMessage: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  actionButtons: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 8,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  approveButton: {
    backgroundColor: '#4CAF50',
  },
  denyButton: {
    backgroundColor: '#f44336',
  },
  actionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  newChatButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#fff6ee',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 12,
    marginLeft: 8,
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#fb7a20',
    shadowColor: '#fb7a20',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  newChatButtonText: {
    color: '#fb7a20',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.2,
  },
  privacySection: {
    marginBottom: 24,
  },
  privacySectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    marginTop: 8,
  },
  privacyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  privacyOptionText: {
    fontSize: 16,
    color: '#fff',
  },
  aboutModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  aboutContent: {
    paddingHorizontal: 20,
  },
  aboutText: {
    fontSize: 16,
    color: '#222',
    lineHeight: 24,
    marginBottom: 16,
  },
  helpModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  helpContent: {
    paddingHorizontal: 20,
  },
  helpSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
    marginTop: 16,
    marginBottom: 12,
  },
  helpQuestion: {
    fontSize: 16,
    fontWeight: '600',
    color: '#222',
    marginTop: 16,
    marginBottom: 4,
  },
  helpAnswer: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    marginBottom: 12,
  },
  helpText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  // Settings modal (orange)
  settingsModalContent: {
    backgroundColor: '#fb7a20',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  // Chat messages modal (full chat)
  chatMessagesModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    height: '45%', // Make the messages modal smaller
    position: 'absolute',
    left: 0,
    right: 0,
    top: '55%', // Position it lower on the screen
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  // Message preview modal (conversation list)
  messagePreviewModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    height: '45%',
    position: 'absolute',
    left: 0,
    right: 0,
    top: '55%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
});

export default profileStyles;